name: Black code style check
on:
  push:
    branches: master
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install & run Black
      run: |
        pip install black
        black --check .
