name: Linux (install, test)
on:
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9.x
    - name: Install requirements
      run: |
        pip install -r requirements.txt
        pip install .
    - name: Run tests
      run: |
        pytest tests/
